export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_RESET = 'CART_RESET';

export const CART_SAVE_SHIPPING_DATA = 'CART_SAVE_SHIPPING_DATA';
export const CART_SAVE_PAYMENT_DATA = 'CART_SAVE_PAYMENT_DATA';